# Generated by Django 4.2.6 on 2025-07-18 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0002_uptimecheck_description_uptimestats_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSLCertificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('issuer', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=95)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_valid', models.BooleanField(default=True)),
                ('signature_algorithm', models.CharField(max_length=50)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_certificate', to='monitoring.website')),
            ],
            options={
                'db_table': 'ssl_certificates',
            },
        ),
        migrations.CreateModel(
            name='SecurityScan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scan_types', models.CharField(choices=[('ssl', 'Ssl'), ('vulnerability', 'Vulnerability'), ('malware', 'Malware'), ('blacklist', 'Blacklist')], max_length=30)),
                ('severity_levels', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=30)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=95)),
                ('is_resolved', models.BooleanField(default=False)),
                ('scan_data', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_scans', to='monitoring.website')),
            ],
            options={
                'db_table': 'scurity_scans',
                'indexes': [models.Index(fields=['website', 'scan_types'], name='scurity_sca_website_b8d1b7_idx'), models.Index(fields=['severity_levels', 'is_resolved'], name='scurity_sca_severit_917258_idx')],
            },
        ),
    ]
