# Generated by Django 4.2.6 on 2025-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='securityscan',
            new_name='security_sc_website_7167a9_idx',
            old_name='scurity_sca_website_b8d1b7_idx',
        ),
        migrations.RenameIndex(
            model_name='securityscan',
            new_name='security_sc_severit_1b2362_idx',
            old_name='scurity_sca_severit_917258_idx',
        ),
        migrations.AddField(
            model_name='securityscan',
            name='recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='securityscan',
            table='security_scans',
        ),
    ]
