# Generated by Django 4.2.6 on 2025-07-19 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('current_state', models.CharField(default='idle', max_length=50)),
                ('context_data', models.JSONField(default=dict)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_session', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_sessions',
            },
        ),
        migrations.CreateModel(
            name='TelegramMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message_type', models.CharField(choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing'), ('command', 'Command'), ('alert', 'Alert')], max_length=55)),
                ('content', models.TextField()),
                ('telegram_message_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_%(class)s_set', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_messages',
                'indexes': [models.Index(fields=['user', 'created_at'], name='telegram_me_user_id_bcbe86_idx'), models.Index(fields=['message_type', 'is_delivered'], name='telegram_me_message_126a1e_idx')],
            },
        ),
    ]
