# Generated by Django 4.2.6 on 2025-07-19 15:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TelegramMessages',
            new_name='TelegramMessage',
        ),
    ]
