services:
  bizguard:
    build: .
    image: bizguard:0.1.0
    container_name: bizguard
    hostname: bizguard
    command: bash initialize/bizguard_initialize.sh
    restart: unless-stopped
    env_file:
      - ./.env
    ports:
      - 8000:8000
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - media_volume:/app/src/media
      - static_volume:/app/src/staticfiles
      - "./src/apps/accounts/migrations:/app/src/apps/accounts/migrations"
      - "./src/apps/monitoring/migrations:/app/src/apps/monitoring/migrations"
      - "./src/apps/security/migrations:/app/src/apps/security/migrations"
      - "./src/apps/alerts/migrations:/app/src/apps/alerts/migrations"
      - "./src/apps/telegram/migrations:/app/src/apps/telegram/migrations"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      bizguard:
        ipv4_address: 192.168.200.3

networks:
  bizguard:
    external: true
    name: bizguard

volumes:
  media_volume:
    name: bizguard_media_volume
  static_volume:
    name: bizguard_static_volume
