# Generated by Django 4.2.6 on 2025-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_rename_website_user_id_1c5543_idx_websites_user_id_c3b78e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uptimecheck',
            name='redirect_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uptimecheck',
            name='uptime',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('error', 'Error'), ('timeout', 'Timeout'), ('redirect', 'Redirect')], max_length=20),
        ),
    ]
