# Generated by Django 4.2.6 on 2025-07-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_uptimecheck_redirect_url_alter_uptimecheck_uptime'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
