# Generated by Django 4.2.6 on 2025-07-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='alertrule',
            name='alert_rules_website_90f538_idx',
        ),
        migrations.RenameField(
            model_name='alertrule',
            old_name='trigger_types',
            new_name='trigger_type',
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['website', 'trigger_type'], name='alert_rules_website_a38bad_idx'),
        ),
    ]
